### ISSUE TITLE
Update name in index

### ISSUE THREAD

**Issue by Kaligule** [Xe/when-then-zen#16]
The [index.md](https://github.com/Xe/when-then-zen/blob/master/index.md) currently states:

> When Then Zen is a new project by Christine Dodrill...

But that doesn't seem to be the authors current name. [Here](https://christine.website/blog/xe-2021-08-07) Xe writes in Xer blog that Xer new name is Xe.

I don't think I ever wrote a proper english sentence with more Xs in it than the last one.

Long story short, if I understood that name thing right then the `index.md` should be updated.

**Comment by Xe** [comment]
Identity is complicated, for professional things like ownership I want to use the name that I use for government and legal interactions. I think it's fine as-is, but I may be updating it to replace my last name as I've just gotten married and haven't decided if I want to assume my husband's last name or not.

**Comment by Kaligule** [comment]
It is complicated indeed. Congratulations on your wedding, I wish you nothing but the best.
