### ISSUE TITLE
Make a website for these articles

### ISSUE THREAD

**Issue by Xe** [Xe/when-then-zen#2]
- fixed width font
- easy on the eyes
- sync all articles offline on first page load (and tell the user about this)
- act as a progressive web app
- instructions on how to add this to your home screen on iOS
- icon
- domain

**Comment by farcaller** [comment]
gatsby does all that. just saying.

**Comment by Xe** [comment]
I'm gonna take a look at Gatsby then. Does it work with markdown files on disk?

**Comment by farcaller** [comment]
it does.
