### ISSUE TITLE
In the Anapana article the Tapering Upwards link is pointing to 404

### ISSUE THREAD

**Issue by Nemin32** [Xe/when-then-zen#7]
On [this](https://when-then-zen.christine.website/meditation/anapana) site, in this sentence:

"The time is intentionally left as a variable so you can decide what session time length to use. If you need help deciding how long to pick, you can always try **tapering upwards** over the course of a month. I find that tapering upwards helps A LOT."

Tapering upwards is a link, but it points to "tapering-upward.feature", a file that doesn't exist, instead of "tapering-upward.md" which does.

**Comment by Nemin32** [comment]
Thanks for the merge! The project is amazing :)

**Comment by Xe** [comment]
No problem. I did a [talk](https://christine.website/talks/webassembly-on-the-server-system-calls-2019-05-31) today so I just only updated the site data now.

Thanks again so much for the correction. I need to figure out a dead link scanner or something.
